"""empty message

Revision ID: 2ab4ba8c5363
Revises: 
Create Date: 2020-10-28 10:08:13.154058

"""
import datetime
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2ab4ba8c5363'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    actors = op.create_table('actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=120), nullable=False),
    sa.Column('surname', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(actors,
    [
        {'firstname':'John', 'surname':'Malkovich', 
                'age':'66', 'gender':'Male'},
        {'firstname':'Jennifer', 'surname':'Lawrence', 
                'age':'30', 'gender':'Female'},
        {'firstname':'Helen', 'surname':'Mirren', 
                'age':'75', 'gender':'Female'},
    ]
    )
    movies = op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.bulk_insert(movies,
    [
        {'title':'Red',
                'release_date':datetime.date(2010, 10, 11)},
        {'title':'Red 2',
                'release_date':datetime.date(2013, 7, 19)},
        {'title':'The Hunger Games',
                'release_date':datetime.date(2012, 3, 12)},
    ]
    )
    projects = op.create_table('projects',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'actor_id')
    )
    op.bulk_insert(projects,
    [
        {'movie_id':1, 'actor_id':1},
        {'movie_id':2, 'actor_id':1},
        {'movie_id':1, 'actor_id':3},
        {'movie_id':2, 'actor_id':3},
        {'movie_id':3, 'actor_id':2},
    ]
    )
    op.create_table('jwt_store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jwt', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    op.drop_table('movies')
    op.drop_table('actors')
    op.drop_table('jwt_store')
    # ### end Alembic commands ###
